name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Ciao, Thank you VERY much for creating this issue. With that you are contributing to the great development of this tool!"
        pr-message: "Thank you very much for this PR. We will review and provide feedback! From the bottom of our hearts, we want to thank you for contributing!"
